version: '2.4'
services:
    #####################
    # Zipkin
    #####################
    zipkin:
        image: "openzipkin/zipkin"
        ports:
            - 9411:9411
        networks:
            - demodapr
         
    #####################
    # Redis
    #####################
    redis:
        image: redis:alpine
        command: [ redis-server, --maxmemory 128mb, --maxmemory-policy volatile-lru, --save "" ]
        networks:
            - demodapr

    #####################
    # Rabbit Queue
    #####################
    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - demodapr


    ############################
    # Mysql
    ############################
    db:
        image: mariadb:10.5
        working_dir: /application
        command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb-file-format=Barracuda, --innodb-large-prefix=1, --innodb-file-per-table=1]
        volumes:
            - ./Pimcore/pimcore-demo-database:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ROOT
            MYSQL_DATABASE: pimcore
            MYSQL_USER: pimcore
            MYSQL_PASSWORD: pimcore
        networks:
            - demodapr

    ############################
    # Pimcore
    ############################
    nginx:
        image: nginx:stable-alpine
        ports:
            - 80:80
        volumes:
            - ./Pimcore:/var/www/html:ro
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php-fpm
            - php-fpm-debug
        networks:
            - demodapr

    php-fpm:
        #user: '1000:1000' # set to your uid:gid
        image: pimcore/pimcore:PHP8.1-fpm
        # ports:
        #     - 9000:9000
        environment:
            DAPR_HTTP_PORT: 3604
            COMPOSER_HOME: /var/www/html
        depends_on:
            - db
        volumes:
            - ./Pimcore:/var/www/html:cached
            - ./Pimcore/pimcore-tmp-storage:/tmp:cached
        networks:
            - demodapr

    php-fpm-debug:
        #user: '33:33' # set to your uid:gid
        image: pimcore/pimcore:PHP8.1-fpm-debug
        environment:
            DAPR_HTTP_PORT: 3605
            XDEBUG_SERVER_NAME: localhost
            XDEBUG_IDE_KEY: pimcore
            XDEBUG_REMOTE_HOST: host.docker.internal
            XDEBUG_REMOTE_CONNECT_BACK: 0
            XDEBUG_REMOTE_PORT: 9003 
            PHP_IDE_CONFIG: "serverName=${XDEBUG_SERVER_NAME}"
            XDEBUG_CONFIG: "idekey=${XDEBUG_IDE_KEY} remote_host=${XDEBUG_REMOTE_HOST} remote_port=${XDEBUG_REMOTE_PORT} max_nesting_level=9999 max_nesting_level=9999 start_with_request=yes mode=debug"
            COMPOSER_HOME: /var/www/html
        depends_on:
            - db
        volumes:
            - ./Pimcore:/var/www/html:cached
            - ./Pimcore/pimcore-tmp-storage:/tmp:cached
        networks:
            - demodapr

    supervisord:
        user: '1000:1000' # set to your uid:gid
        image: pimcore/pimcore:PHP8.1-supervisord
        depends_on:
            - db
        volumes:
            - ./Pimcore:/var/www/html:cached
            - ./docker/supervisord.conf:/etc/supervisor/conf.d/pimcore.conf:ro
        networks:
            - demodapr

    php-fpm-dapr:
        image: "daprio/dapr:edge"
        command: [
            "./daprd",
            "-app-id", "php-fpm",
            "-app-port", "80",
            "-dapr-http-port", "3604",
            "-dapr-grpc-port", "50004",
            "-components-path", "./components",
            "-config", "./configuration/config.yaml"]
        volumes:
            - "./Dapr/components/:/components"
            - "./Dapr/configuration/:/configuration"
        depends_on:
            - php-fpm
        network_mode: "service:php-fpm"

    php-fpm-debug-dapr:
        image: "daprio/dapr:edge"
        command: [
            "./daprd",
            "-app-id", "php-fpm-debug",
            "-app-port", "80",
            "-dapr-http-port", "3605",
            "-dapr-grpc-port", "50005",
            "-components-path", "./components",
            "-config", "./configuration/config.yaml"]
        volumes:
            - "./Dapr/components/:/components"
            - "./Dapr/configuration/:/configuration"
        depends_on:
            - php-fpm-debug
        network_mode: "service:php-fpm-debug"

    ############################
    # Order PubSub
    ############################
    productsub:
        build:
            context: ./ProductSubscriber/
            dockerfile: Dockerfile
        ports:
            - 6002:80
        depends_on:
            - rabbitmq
        networks:
            - demodapr
        
    productsub-dapr:
        image: "daprio/dapr:edge"
        command: [
            "./daprd",         
            "-app-id", "productsub",
            "-app-port", "80",
            "-dapr-http-port", "3602",
            "-dapr-grpc-port", "50002",
            "-components-path", "./components",
            "-config", "./configuration/config.yaml"]
        volumes:
            - "./Dapr/components/:/components"
            - "./Dapr/configuration/:/configuration"
        depends_on:
            - productsub
        network_mode: "service:productsub"

    ############################
    # Dapr placement service
    ############################
    # placement:
    #     image: "daprio/dapr"
    #     command: ["./placement", "-port", "50006"]
    #     ports:
    #     - "50006:50006"
    #     networks:
    #     - demodapr

volumes:
    pimcore-demo-database:
    pimcore-tmp-storage:

networks:
  demodapr:
