TYPE=VIEW
query=select `pimcore`.`object_query_NE`.`oo_id` AS `oo_id`,`pimcore`.`object_query_NE`.`oo_classId` AS `oo_classId`,`pimcore`.`object_query_NE`.`oo_className` AS `oo_className`,`pimcore`.`object_query_NE`.`date` AS `date`,`pimcore`.`object_query_NE`.`gallery__images` AS `gallery__images`,`pimcore`.`object_query_NE`.`gallery__hotspots` AS `gallery__hotspots`,`pimcore`.`objects`.`o_id` AS `o_id`,`pimcore`.`objects`.`o_parentId` AS `o_parentId`,`pimcore`.`objects`.`o_type` AS `o_type`,`pimcore`.`objects`.`o_key` AS `o_key`,`pimcore`.`objects`.`o_path` AS `o_path`,`pimcore`.`objects`.`o_index` AS `o_index`,`pimcore`.`objects`.`o_published` AS `o_published`,`pimcore`.`objects`.`o_creationDate` AS `o_creationDate`,`pimcore`.`objects`.`o_modificationDate` AS `o_modificationDate`,`pimcore`.`objects`.`o_userOwner` AS `o_userOwner`,`pimcore`.`objects`.`o_userModification` AS `o_userModification`,`pimcore`.`objects`.`o_classId` AS `o_classId`,`pimcore`.`objects`.`o_className` AS `o_className`,`pimcore`.`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`pimcore`.`objects`.`o_childrenSortOrder` AS `o_childrenSortOrder`,`pimcore`.`objects`.`o_versionCount` AS `o_versionCount`,`fr`.`ooo_id` AS `ooo_id`,`fr`.`language` AS `language`,`fr`.`title` AS `title`,`fr`.`shortText` AS `shortText` from ((`pimcore`.`object_query_NE` join `pimcore`.`objects` on(`pimcore`.`objects`.`o_id` = `pimcore`.`object_query_NE`.`oo_id`)) left join `pimcore`.`object_localized_query_NE_fr` `fr` on(1 and `pimcore`.`object_query_NE`.`oo_id` = `fr`.`ooo_id`))
md5=bae2bcc286f065cde999e917cab89517
updatable=0
algorithm=0
definer_user=pimcore
definer_host=%
suid=2
with_check_option=0
timestamp=2022-03-16 03:51:30
create-version=2
source=SELECT `oo_id`,`oo_classId`,`oo_className`,`date`,`gallery__images`,`gallery__hotspots`,`o_id`,`o_parentId`,`o_type`,`o_key`,`o_path`,`o_index`,`o_published`,`o_creationDate`,`o_modificationDate`,`o_userOwner`,`o_userModification`,`o_classId`,`o_className`,`o_childrenSortBy`,`o_childrenSortOrder`,`o_versionCount`,`fr`.`ooo_id`,`fr`.`language`,`fr`.`title` as "title",`fr`.`shortText` as "shortText"\nFROM `object_query_NE`\n    JOIN `objects`\n        ON (`objects`.`o_id` = `object_query_NE`.`oo_id`)LEFT JOIN object_localized_query_NE_fr as `fr`\n    ON( 1\n        AND object_query_NE.oo_id = fr.ooo_id\n    )
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `pimcore`.`object_query_NE`.`oo_id` AS `oo_id`,`pimcore`.`object_query_NE`.`oo_classId` AS `oo_classId`,`pimcore`.`object_query_NE`.`oo_className` AS `oo_className`,`pimcore`.`object_query_NE`.`date` AS `date`,`pimcore`.`object_query_NE`.`gallery__images` AS `gallery__images`,`pimcore`.`object_query_NE`.`gallery__hotspots` AS `gallery__hotspots`,`pimcore`.`objects`.`o_id` AS `o_id`,`pimcore`.`objects`.`o_parentId` AS `o_parentId`,`pimcore`.`objects`.`o_type` AS `o_type`,`pimcore`.`objects`.`o_key` AS `o_key`,`pimcore`.`objects`.`o_path` AS `o_path`,`pimcore`.`objects`.`o_index` AS `o_index`,`pimcore`.`objects`.`o_published` AS `o_published`,`pimcore`.`objects`.`o_creationDate` AS `o_creationDate`,`pimcore`.`objects`.`o_modificationDate` AS `o_modificationDate`,`pimcore`.`objects`.`o_userOwner` AS `o_userOwner`,`pimcore`.`objects`.`o_userModification` AS `o_userModification`,`pimcore`.`objects`.`o_classId` AS `o_classId`,`pimcore`.`objects`.`o_className` AS `o_className`,`pimcore`.`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`pimcore`.`objects`.`o_childrenSortOrder` AS `o_childrenSortOrder`,`pimcore`.`objects`.`o_versionCount` AS `o_versionCount`,`fr`.`ooo_id` AS `ooo_id`,`fr`.`language` AS `language`,`fr`.`title` AS `title`,`fr`.`shortText` AS `shortText` from ((`pimcore`.`object_query_NE` join `pimcore`.`objects` on(`pimcore`.`objects`.`o_id` = `pimcore`.`object_query_NE`.`oo_id`)) left join `pimcore`.`object_localized_query_NE_fr` `fr` on(1 and `pimcore`.`object_query_NE`.`oo_id` = `fr`.`ooo_id`))
mariadb-version=100515
