TYPE=VIEW
query=select `pimcore`.`object_query_EF_OTO`.`oo_id` AS `oo_id`,`pimcore`.`object_query_EF_OTO`.`oo_classId` AS `oo_classId`,`pimcore`.`object_query_EF_OTO`.`oo_className` AS `oo_className`,`pimcore`.`object_query_EF_OTO`.`offernumber` AS `offernumber`,`pimcore`.`object_query_EF_OTO`.`dateCreated` AS `dateCreated`,`pimcore`.`object_query_EF_OTO`.`dateValidUntil` AS `dateValidUntil`,`pimcore`.`object_query_EF_OTO`.`totalPriceBeforeDiscount` AS `totalPriceBeforeDiscount`,`pimcore`.`object_query_EF_OTO`.`totalPrice` AS `totalPrice`,`pimcore`.`object_query_EF_OTO`.`discountType` AS `discountType`,`pimcore`.`object_query_EF_OTO`.`discount` AS `discount`,`pimcore`.`object_query_EF_OTO`.`cartId` AS `cartId`,`pimcore`.`object_query_EF_OTO`.`items` AS `items`,`pimcore`.`object_query_EF_OTO`.`customItems` AS `customItems`,`pimcore`.`objects`.`o_id` AS `o_id`,`pimcore`.`objects`.`o_parentId` AS `o_parentId`,`pimcore`.`objects`.`o_type` AS `o_type`,`pimcore`.`objects`.`o_key` AS `o_key`,`pimcore`.`objects`.`o_path` AS `o_path`,`pimcore`.`objects`.`o_index` AS `o_index`,`pimcore`.`objects`.`o_published` AS `o_published`,`pimcore`.`objects`.`o_creationDate` AS `o_creationDate`,`pimcore`.`objects`.`o_modificationDate` AS `o_modificationDate`,`pimcore`.`objects`.`o_userOwner` AS `o_userOwner`,`pimcore`.`objects`.`o_userModification` AS `o_userModification`,`pimcore`.`objects`.`o_classId` AS `o_classId`,`pimcore`.`objects`.`o_className` AS `o_className`,`pimcore`.`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`pimcore`.`objects`.`o_childrenSortOrder` AS `o_childrenSortOrder`,`pimcore`.`objects`.`o_versionCount` AS `o_versionCount` from (`pimcore`.`object_query_EF_OTO` join `pimcore`.`objects` on(`pimcore`.`objects`.`o_id` = `pimcore`.`object_query_EF_OTO`.`oo_id`))
md5=eb02f8433138e7f1cc919b7aaa426147
updatable=1
algorithm=0
definer_user=pimcore
definer_host=%
suid=2
with_check_option=0
timestamp=2022-03-16 03:51:30
create-version=2
source=SELECT * FROM `object_query_EF_OTO` JOIN `objects` ON `objects`.`o_id` = `object_query_EF_OTO`.`oo_id`
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `pimcore`.`object_query_EF_OTO`.`oo_id` AS `oo_id`,`pimcore`.`object_query_EF_OTO`.`oo_classId` AS `oo_classId`,`pimcore`.`object_query_EF_OTO`.`oo_className` AS `oo_className`,`pimcore`.`object_query_EF_OTO`.`offernumber` AS `offernumber`,`pimcore`.`object_query_EF_OTO`.`dateCreated` AS `dateCreated`,`pimcore`.`object_query_EF_OTO`.`dateValidUntil` AS `dateValidUntil`,`pimcore`.`object_query_EF_OTO`.`totalPriceBeforeDiscount` AS `totalPriceBeforeDiscount`,`pimcore`.`object_query_EF_OTO`.`totalPrice` AS `totalPrice`,`pimcore`.`object_query_EF_OTO`.`discountType` AS `discountType`,`pimcore`.`object_query_EF_OTO`.`discount` AS `discount`,`pimcore`.`object_query_EF_OTO`.`cartId` AS `cartId`,`pimcore`.`object_query_EF_OTO`.`items` AS `items`,`pimcore`.`object_query_EF_OTO`.`customItems` AS `customItems`,`pimcore`.`objects`.`o_id` AS `o_id`,`pimcore`.`objects`.`o_parentId` AS `o_parentId`,`pimcore`.`objects`.`o_type` AS `o_type`,`pimcore`.`objects`.`o_key` AS `o_key`,`pimcore`.`objects`.`o_path` AS `o_path`,`pimcore`.`objects`.`o_index` AS `o_index`,`pimcore`.`objects`.`o_published` AS `o_published`,`pimcore`.`objects`.`o_creationDate` AS `o_creationDate`,`pimcore`.`objects`.`o_modificationDate` AS `o_modificationDate`,`pimcore`.`objects`.`o_userOwner` AS `o_userOwner`,`pimcore`.`objects`.`o_userModification` AS `o_userModification`,`pimcore`.`objects`.`o_classId` AS `o_classId`,`pimcore`.`objects`.`o_className` AS `o_className`,`pimcore`.`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`pimcore`.`objects`.`o_childrenSortOrder` AS `o_childrenSortOrder`,`pimcore`.`objects`.`o_versionCount` AS `o_versionCount` from (`pimcore`.`object_query_EF_OTO` join `pimcore`.`objects` on(`pimcore`.`objects`.`o_id` = `pimcore`.`object_query_EF_OTO`.`oo_id`))
mariadb-version=100515
