TYPE=VIEW
query=select `pimcore`.`object_query_CU`.`oo_id` AS `oo_id`,`pimcore`.`object_query_CU`.`oo_classId` AS `oo_classId`,`pimcore`.`object_query_CU`.`oo_className` AS `oo_className`,`pimcore`.`object_query_CU`.`active` AS `active`,`pimcore`.`object_query_CU`.`gender` AS `gender`,`pimcore`.`object_query_CU`.`firstname` AS `firstname`,`pimcore`.`object_query_CU`.`lastname` AS `lastname`,`pimcore`.`object_query_CU`.`email` AS `email`,`pimcore`.`object_query_CU`.`street` AS `street`,`pimcore`.`object_query_CU`.`zip` AS `zip`,`pimcore`.`object_query_CU`.`city` AS `city`,`pimcore`.`object_query_CU`.`countryCode` AS `countryCode`,`pimcore`.`object_query_CU`.`phone` AS `phone`,`pimcore`.`object_query_CU`.`idEncoded` AS `idEncoded`,`pimcore`.`object_query_CU`.`manualSegments` AS `manualSegments`,`pimcore`.`object_query_CU`.`calculatedSegments` AS `calculatedSegments`,`pimcore`.`object_query_CU`.`password` AS `password`,`pimcore`.`object_query_CU`.`ssoIdentities` AS `ssoIdentities`,`pimcore`.`object_query_CU`.`company` AS `company`,`pimcore`.`object_query_CU`.`passwordRecoveryToken` AS `passwordRecoveryToken`,`pimcore`.`object_query_CU`.`passwordRecoveryTokenDate` AS `passwordRecoveryTokenDate`,`pimcore`.`object_query_CU`.`customerLanguage` AS `customerLanguage`,`pimcore`.`object_query_CU`.`newsletter` AS `newsletter`,`pimcore`.`object_query_CU`.`newsletterConfirmed` AS `newsletterConfirmed`,`pimcore`.`object_query_CU`.`profiling` AS `profiling`,`pimcore`.`object_query_CU`.`newsletterConfirmToken` AS `newsletterConfirmToken`,`pimcore`.`objects`.`o_id` AS `o_id`,`pimcore`.`objects`.`o_parentId` AS `o_parentId`,`pimcore`.`objects`.`o_type` AS `o_type`,`pimcore`.`objects`.`o_key` AS `o_key`,`pimcore`.`objects`.`o_path` AS `o_path`,`pimcore`.`objects`.`o_index` AS `o_index`,`pimcore`.`objects`.`o_published` AS `o_published`,`pimcore`.`objects`.`o_creationDate` AS `o_creationDate`,`pimcore`.`objects`.`o_modificationDate` AS `o_modificationDate`,`pimcore`.`objects`.`o_userOwner` AS `o_userOwner`,`pimcore`.`objects`.`o_userModification` AS `o_userModification`,`pimcore`.`objects`.`o_classId` AS `o_classId`,`pimcore`.`objects`.`o_className` AS `o_className`,`pimcore`.`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`pimcore`.`objects`.`o_childrenSortOrder` AS `o_childrenSortOrder`,`pimcore`.`objects`.`o_versionCount` AS `o_versionCount` from (`pimcore`.`object_query_CU` join `pimcore`.`objects` on(`pimcore`.`objects`.`o_id` = `pimcore`.`object_query_CU`.`oo_id`))
md5=a4f8371100e06bdc4125797b2dc18a55
updatable=1
algorithm=0
definer_user=pimcore
definer_host=%
suid=2
with_check_option=0
timestamp=2022-03-16 03:51:30
create-version=2
source=SELECT * FROM `object_query_CU` JOIN `objects` ON `objects`.`o_id` = `object_query_CU`.`oo_id`
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `pimcore`.`object_query_CU`.`oo_id` AS `oo_id`,`pimcore`.`object_query_CU`.`oo_classId` AS `oo_classId`,`pimcore`.`object_query_CU`.`oo_className` AS `oo_className`,`pimcore`.`object_query_CU`.`active` AS `active`,`pimcore`.`object_query_CU`.`gender` AS `gender`,`pimcore`.`object_query_CU`.`firstname` AS `firstname`,`pimcore`.`object_query_CU`.`lastname` AS `lastname`,`pimcore`.`object_query_CU`.`email` AS `email`,`pimcore`.`object_query_CU`.`street` AS `street`,`pimcore`.`object_query_CU`.`zip` AS `zip`,`pimcore`.`object_query_CU`.`city` AS `city`,`pimcore`.`object_query_CU`.`countryCode` AS `countryCode`,`pimcore`.`object_query_CU`.`phone` AS `phone`,`pimcore`.`object_query_CU`.`idEncoded` AS `idEncoded`,`pimcore`.`object_query_CU`.`manualSegments` AS `manualSegments`,`pimcore`.`object_query_CU`.`calculatedSegments` AS `calculatedSegments`,`pimcore`.`object_query_CU`.`password` AS `password`,`pimcore`.`object_query_CU`.`ssoIdentities` AS `ssoIdentities`,`pimcore`.`object_query_CU`.`company` AS `company`,`pimcore`.`object_query_CU`.`passwordRecoveryToken` AS `passwordRecoveryToken`,`pimcore`.`object_query_CU`.`passwordRecoveryTokenDate` AS `passwordRecoveryTokenDate`,`pimcore`.`object_query_CU`.`customerLanguage` AS `customerLanguage`,`pimcore`.`object_query_CU`.`newsletter` AS `newsletter`,`pimcore`.`object_query_CU`.`newsletterConfirmed` AS `newsletterConfirmed`,`pimcore`.`object_query_CU`.`profiling` AS `profiling`,`pimcore`.`object_query_CU`.`newsletterConfirmToken` AS `newsletterConfirmToken`,`pimcore`.`objects`.`o_id` AS `o_id`,`pimcore`.`objects`.`o_parentId` AS `o_parentId`,`pimcore`.`objects`.`o_type` AS `o_type`,`pimcore`.`objects`.`o_key` AS `o_key`,`pimcore`.`objects`.`o_path` AS `o_path`,`pimcore`.`objects`.`o_index` AS `o_index`,`pimcore`.`objects`.`o_published` AS `o_published`,`pimcore`.`objects`.`o_creationDate` AS `o_creationDate`,`pimcore`.`objects`.`o_modificationDate` AS `o_modificationDate`,`pimcore`.`objects`.`o_userOwner` AS `o_userOwner`,`pimcore`.`objects`.`o_userModification` AS `o_userModification`,`pimcore`.`objects`.`o_classId` AS `o_classId`,`pimcore`.`objects`.`o_className` AS `o_className`,`pimcore`.`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`pimcore`.`objects`.`o_childrenSortOrder` AS `o_childrenSortOrder`,`pimcore`.`objects`.`o_versionCount` AS `o_versionCount` from (`pimcore`.`object_query_CU` join `pimcore`.`objects` on(`pimcore`.`objects`.`o_id` = `pimcore`.`object_query_CU`.`oo_id`))
mariadb-version=100515
